// <auto-generated />
using System;
using JForms.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JForms.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190829064747_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("JForms.API.Data.Entity.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.FormField", b =>
                {
                    b.Property<int>("FormFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("FormFieldId");

                    b.HasIndex("FormId");

                    b.ToTable("FormField");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.FormSubmission", b =>
                {
                    b.Property<int>("FormSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("FormSubmissionId");

                    b.HasIndex("FormId");

                    b.ToTable("FormSubmission");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.FormSubmissionValue", b =>
                {
                    b.Property<int>("FormSubmissionValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FieldFormFieldId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionFormSubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("FormSubmissionValueId");

                    b.HasIndex("FieldFormFieldId");

                    b.HasIndex("SubmissionFormSubmissionId");

                    b.ToTable("FormSubmissionValue");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.Form", b =>
                {
                    b.HasOne("JForms.API.Data.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.FormField", b =>
                {
                    b.HasOne("JForms.API.Data.Entity.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.FormSubmission", b =>
                {
                    b.HasOne("JForms.API.Data.Entity.Form", "Form")
                        .WithMany("Submissions")
                        .HasForeignKey("FormId");
                });

            modelBuilder.Entity("JForms.API.Data.Entity.FormSubmissionValue", b =>
                {
                    b.HasOne("JForms.API.Data.Entity.FormField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldFormFieldId");

                    b.HasOne("JForms.API.Data.Entity.FormSubmission", "Submission")
                        .WithMany("Values")
                        .HasForeignKey("SubmissionFormSubmissionId");
                });
#pragma warning restore 612, 618
        }
    }
}
