// <auto-generated />
using System;
using JForms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JForms.Data.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20190908060617_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview9.19423.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("JForms.Data.Entity.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormField", b =>
                {
                    b.Property<int>("FormFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("TypeFormFieldTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidationFormFieldValidationId")
                        .HasColumnType("integer");

                    b.HasKey("FormFieldId");

                    b.HasIndex("FormId");

                    b.HasIndex("TypeFormFieldTypeId");

                    b.HasIndex("ValidationFormFieldValidationId");

                    b.ToTable("FormField");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormFieldOption", b =>
                {
                    b.Property<int>("FormFieldOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FormFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("FormFieldOptionId");

                    b.HasIndex("FormFieldId");

                    b.ToTable("FormFieldOption");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormFieldType", b =>
                {
                    b.Property<int>("FormFieldTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("MultipleOptions")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("FormFieldTypeId");

                    b.ToTable("FormFieldTypes");

                    b.HasData(
                        new
                        {
                            FormFieldTypeId = 1,
                            MultipleOptions = false,
                            Name = "String"
                        },
                        new
                        {
                            FormFieldTypeId = 2,
                            MultipleOptions = false,
                            Name = "Number"
                        },
                        new
                        {
                            FormFieldTypeId = 3,
                            MultipleOptions = false,
                            Name = "Date"
                        },
                        new
                        {
                            FormFieldTypeId = 4,
                            MultipleOptions = false,
                            Name = "RadioButton"
                        },
                        new
                        {
                            FormFieldTypeId = 5,
                            MultipleOptions = false,
                            Name = "DropDown"
                        },
                        new
                        {
                            FormFieldTypeId = 6,
                            MultipleOptions = false,
                            Name = "MultiSelect"
                        });
                });

            modelBuilder.Entity("JForms.Data.Entity.FormFieldTypeRuleType", b =>
                {
                    b.Property<int>("FormFieldTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FormValidationRuleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("FormFieldTypeId", "FormValidationRuleTypeId");

                    b.HasIndex("FormValidationRuleTypeId");

                    b.ToTable("FormFieldTypeRuleType");

                    b.HasData(
                        new
                        {
                            FormFieldTypeId = 1,
                            FormValidationRuleTypeId = 1
                        },
                        new
                        {
                            FormFieldTypeId = 1,
                            FormValidationRuleTypeId = 4
                        },
                        new
                        {
                            FormFieldTypeId = 1,
                            FormValidationRuleTypeId = 5
                        },
                        new
                        {
                            FormFieldTypeId = 2,
                            FormValidationRuleTypeId = 1
                        },
                        new
                        {
                            FormFieldTypeId = 2,
                            FormValidationRuleTypeId = 2
                        },
                        new
                        {
                            FormFieldTypeId = 2,
                            FormValidationRuleTypeId = 3
                        });
                });

            modelBuilder.Entity("JForms.Data.Entity.FormFieldValidation", b =>
                {
                    b.Property<int>("FormFieldValidationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("FormFieldValidationId");

                    b.ToTable("FormFieldValidation");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormOrigin", b =>
                {
                    b.Property<int>("FormOriginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("FormOriginId");

                    b.HasIndex("FormId");

                    b.ToTable("FormOrigin");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormSubmission", b =>
                {
                    b.Property<int>("FormSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("FormSubmissionId");

                    b.HasIndex("FormId");

                    b.ToTable("FormSubmission");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormSubmissionValue", b =>
                {
                    b.Property<int>("FormSubmissionValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FieldFormFieldId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionFormSubmissionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("FormSubmissionValueId");

                    b.HasIndex("FieldFormFieldId");

                    b.HasIndex("SubmissionFormSubmissionId");

                    b.ToTable("FormSubmissionValue");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormValidationRule", b =>
                {
                    b.Property<int>("FormValidationRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Constraint")
                        .HasColumnType("text");

                    b.Property<int?>("FormFieldValidationId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeFormValidationRuleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("FormValidationRuleId");

                    b.HasIndex("FormFieldValidationId");

                    b.HasIndex("TypeFormValidationRuleTypeId");

                    b.ToTable("FormValidationRule");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormValidationRuleType", b =>
                {
                    b.Property<int>("FormValidationRuleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("FormValidationRuleTypeId");

                    b.ToTable("FormValidationRuleTypes");

                    b.HasData(
                        new
                        {
                            FormValidationRuleTypeId = 1,
                            Name = "Required"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 2,
                            Name = "NumberMin"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 3,
                            Name = "NumberMax"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 4,
                            Name = "StringMin"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 5,
                            Name = "StringMax"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 6,
                            Name = "DateMin"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 7,
                            Name = "DateMax"
                        },
                        new
                        {
                            FormValidationRuleTypeId = 8,
                            Name = "Regex"
                        });
                });

            modelBuilder.Entity("JForms.Data.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JForms.Data.Entity.Form", b =>
                {
                    b.HasOne("JForms.Data.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormField", b =>
                {
                    b.HasOne("JForms.Data.Entity.Form", null)
                        .WithMany("Fields")
                        .HasForeignKey("FormId");

                    b.HasOne("JForms.Data.Entity.FormFieldType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeFormFieldTypeId");

                    b.HasOne("JForms.Data.Entity.FormFieldValidation", "Validation")
                        .WithMany()
                        .HasForeignKey("ValidationFormFieldValidationId");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormFieldOption", b =>
                {
                    b.HasOne("JForms.Data.Entity.FormField", null)
                        .WithMany("Options")
                        .HasForeignKey("FormFieldId");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormFieldTypeRuleType", b =>
                {
                    b.HasOne("JForms.Data.Entity.FormFieldType", "FormFieldType")
                        .WithMany("FormFieldTypeRuleType")
                        .HasForeignKey("FormFieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JForms.Data.Entity.FormValidationRuleType", "FormValidationRuleType")
                        .WithMany("FormFieldTypeRuleType")
                        .HasForeignKey("FormValidationRuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JForms.Data.Entity.FormOrigin", b =>
                {
                    b.HasOne("JForms.Data.Entity.Form", null)
                        .WithMany("Origins")
                        .HasForeignKey("FormId");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormSubmission", b =>
                {
                    b.HasOne("JForms.Data.Entity.Form", "Form")
                        .WithMany("Submissions")
                        .HasForeignKey("FormId");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormSubmissionValue", b =>
                {
                    b.HasOne("JForms.Data.Entity.FormField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldFormFieldId");

                    b.HasOne("JForms.Data.Entity.FormSubmission", "Submission")
                        .WithMany("Values")
                        .HasForeignKey("SubmissionFormSubmissionId");
                });

            modelBuilder.Entity("JForms.Data.Entity.FormValidationRule", b =>
                {
                    b.HasOne("JForms.Data.Entity.FormFieldValidation", null)
                        .WithMany("Rules")
                        .HasForeignKey("FormFieldValidationId");

                    b.HasOne("JForms.Data.Entity.FormValidationRuleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeFormValidationRuleTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
